# Generated by Django 4.2.5 on 2023-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihpredict', '0005_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.TextField(null=True),
        ),
    ]
