# Generated by Django 4.2.5 on 2023-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihpredict', '0006_news_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sentiment',
            field=models.TextField(default='neutral'),
        ),
    ]
